# Generated by Django 3.0.4 on 2020-03-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images', verbose_name='Photo'),
        ),
    ]
